### ISSUE TITLE
The correspondence between the predictions, embeddings data and model

### ISSUE THREAD

**Issue by marvelcell** [rvivek3/AnchorPoints#2]
Thank you for your outstanding work, it really helps me a lot!

I notice that you've released the predictions and embeddings data of the models you mentioned in paper, but I can't find the corresponding relationship between the data and the model, and I don't know which prediction data comes from which model.
Could you please explain that? 

Thank you very much, and thank you for your excellent work again!

**Comment by rvivek3** [comment]
Hi marvelcell, I'm glad our work is helpful! I just pushed model_names.py which provides the order of the model+prompt pairs corresponding to the prediction data. 

The order of the data points matches their order in the hugging face dataset.

Let me know if you have any questions.

**Comment by marvelcell** [comment]
Your response has solved my question, thank you very much!

**Comment by marvelcell** [comment]
Hi, I've noticed that there is an "SetFit" folder for mnli dataset, but there isn't data for the "SetFit" in data.zip, may I ask for that? Thank you very much!

**Comment by rvivek3** [comment]
SetFit just refers to the Hugging Face org which uploaded the MNLI data:  https://huggingface.co/datasets/SetFit/mnli.

This should match the official MNLI dataset. All references to MNLI in our work refers to this data.

**Comment by marvelcell** [comment]
Thank you!
